version: '3.8'

services:
  sqlserver:
    build:
      context: ./requirements/sqlserver
      dockerfile: Dockerfile
    image: sqlserver-image
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - sqlserver-net

volumes:
  sqlserver_data:
    driver: local
    driver_opts:
      type: none
      device: /home/srandria/data/sqlserver_data
      o: bind

networks:
  sqlserver-net:
    driver: bridge
